apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
# https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes
